# Generated by Django 5.1.7 on 2025-12-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=200)),
                ('player_name', models.CharField(default='Anonymous', max_length=200)),
                ('game_version', models.CharField(default='Unknown', max_length=50)),
                ('team_hash', models.CharField(db_index=True, max_length=64)),
                ('battle_fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('victory', models.BooleanField(default=True)),
                ('battle_start_time', models.BigIntegerField()),
                ('battle_end_time', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['battle_fingerprint'], name='portfolioap_battle__303b7b_idx'), models.Index(fields=['trainer_name', 'player_name'], name='portfolioap_trainer_09469b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BattlePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('pokemon_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('shiny', models.BooleanField(default=False)),
                ('stats', models.JSONField()),
                ('ivs', models.JSONField()),
                ('nature', models.CharField(max_length=20)),
                ('current_hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('type1', models.CharField(max_length=20)),
                ('type2', models.CharField(blank=True, max_length=20, null=True)),
                ('ability', models.CharField(max_length=50)),
                ('ability_slot', models.IntegerField()),
                ('moveset', models.JSONField()),
                ('moveset_details', models.JSONField()),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('ball', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(max_length=20)),
                ('fainted', models.BooleanField(default=False)),
                ('happiness', models.IntegerField()),
                ('met_at', models.CharField(blank=True, max_length=100, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('kill_list', models.JSONField(blank=True, null=True)),
                ('died', models.BooleanField(default=False)),
                ('killer', models.CharField(blank=True, max_length=100, null=True)),
                ('evolved', models.BooleanField(default=False)),
                ('evo_id', models.IntegerField(blank=True, null=True)),
                ('evo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='portfolioapp.trainerbattle')),
            ],
        ),
    ]
