# Generated by Django 5.1.7 on 2026-01-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepokemon',
            name='switch_ins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battlepokemon',
            name='turns',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
