# Generated by Django 5.1.7 on 2026-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_battlepokemon_switch_ins_battlepokemon_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbattle',
            name='lead',
            field=models.IntegerField(default=0),
        ),
    ]
