# Generated by Django 5.1.7 on 2026-01-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_trainerbattle_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepokemon',
            name='damage_dealt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='battlepokemon',
            name='damage_taken',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='battlepokemon',
            name='pp_used',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
