# Generated by Django 5.1.7 on 2026-05-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_battlepokemon_damage_dealt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerbattle',
            name='bages',
            field=models.IntegerField(default=0),
        ),
    ]
