# Generated by Django 5.1.7 on 2026-05-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_trainerbattle_bages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerbattle',
            old_name='bages',
            new_name='badges',
        ),
    ]
